name: climetlab
channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - pandas
  - xarray>=0.19.0
  - zarr
  - dask
  - s3fs
  - netcdf4
  - cfgrib>=0.9.8.4
  - magics>=1.5.6
  - toolz
  - filelock
  - pyyaml
  - markdown
  - termcolor
  - jellyfish
  - entrypoints
  - pip
  - branca==0.3.1
  - tensorflow
  - skinnywms
  - folium>=0.12.1
  - pip:
      - eccodes-python
      - ecmwf-api-client>=1.6.1
      - cdsapi
      - tqdm
      - requests
      - ecmwflibs>=0.1.2
      - pdbufr
      - pyodc
